# Generated by Django 5.1.2 on 2024-10-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='time',
            new_name='date',
        ),
    ]
